language: go
go:
  - "1.10"
  - "1.11"
  - "1.12"


install:
  - go get -v .

before_script:
  - go vet -v ./...
script:
  - echo $TRAVIS_GO_VERSION; go test -race -v -timeout 60s ./... -tags=nointegration
