language: go
go:
  - "1.13.x"
  - "1.14.x"

install:
  - true # We do nothing here to avoid the default travis_install_go_dependencies script from running `go get`
env:
   GOFLAGS=-mod=vendor
before_script:
  - go vet -v ./...
script:
  - echo $TRAVIS_GO_VERSION; go test -race -v -timeout 2m -failfast ./... -tags=nointegration
  - echo $TRAVIS_GO_VERSION; go test -race -v -timeout 2m -failfast ./cmd/... # integration tests
