[[constraint]]
  name = "github.com/DataDog/datadog-go"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/armon/go-proxyproto"

[[constraint]]
  branch = "master"
  name = "github.com/stripe/go-einhorn"

[[constraint]]
  name = "github.com/elazarl/goproxy"
  source = "git@github.com:stripe/goproxy.git"
  # We previously pinned to 0890fc15d1b6428a674b8252a2d238ca589daf73
  # to avoid introducing a timeout bug that was introduced after that commit.
  # We've subsequently switched to our own fork of goproxy, and the master branch
  # of our fork has reverted that bug.
  revision = "7d72f050809adb6424b4f729619fa290eeb5f253"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  version = "v1.20.0"
  name = "gopkg.in/urfave/cli.v1"

[[constraint]]
  version = "v2"
  name = "gopkg.in/yaml.v2"