[[constraint]]
  name = "github.com/DataDog/datadog-go"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/armon/go-proxyproto"

[[constraint]]
  branch = "master"
  name = "github.com/stripe/go-einhorn"

[[constraint]]
  name = "github.com/elazarl/goproxy"
  source = "git@github.com:stripe/goproxy.git"
  # We maintain our own forked version of goproxy v1.1 which allows us
  # to pass context to the net.Dial family of functions.
  revision = "31709788377d16eea06bf97a669f7e96e5647412"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  version = "v1.20.0"
  name = "gopkg.in/urfave/cli.v1"

[[constraint]]
  version = "v2"
  name = "gopkg.in/yaml.v2"
