[[constraint]]
  name = "github.com/DataDog/datadog-go"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/armon/go-proxyproto"

[[constraint]]
  branch = "master"
  name = "github.com/stripe/go-einhorn"

[[constraint]]
  name = "github.com/elazarl/goproxy"
  source = "git@github.com:stripe/goproxy.git"
  # We maintain own fork of goproxy based on the v1.1 release
  revision = "e34c7f6dab2815c58b0d891a345ab31d0d8e215d"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  version = "v1.20.0"
  name = "gopkg.in/urfave/cli.v1"

[[constraint]]
  version = "v2"
  name = "gopkg.in/yaml.v2"
